---
title: "R Notebook"
output: html_notebook
---

This is based on the tutorial
https://github.com/IanevskiAleksandr/sc-type

# load libraries and functions

```{r load libraries and functions, echo=FALSE}
rm(list=ls())
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(HGNChelper))
suppressMessages(library(openxlsx))
suppressMessages(library(dittoSeq))

source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

```


# load data

```{r load data, echo=FALSE}
# load data
bm <- readRDS("data/seurat_obj/Oejten_seurat_QC.rds")
# load gene database, provided
gs_list <- gene_sets_prepare("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_short.xlsx", "Immune system")
```

# run sc-type

```{r run sc-type, echo=FALSE}
# run sc-type
es.max <- sctype_score(scRNAseqData = bm[["RNA"]]@scale.data,
                       scaled = TRUE,
                       gs = gs_list$gs_positive,
                       gs2 = gs_list$gs_negative)
```


# merge by cluster

```{r merge by cluster, echo=FALSE}

cL_resutls <- do.call("rbind", lapply(unique(bm@meta.data$seurat_clusters), function(cl){
    es.max.cl <- sort(rowSums(es.max[ ,rownames(bm@meta.data[bm@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(bm@meta.data$seurat_clusters==cl)), 10)
}))
sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)

# set low-confident (low ScType score) clusters to "unknown"
sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] <- "Unknown"
print(sctype_scores[,1:3])
# save results to csv and xlsx
write.csv(sctype_scores, "results/tables/sctype_scores.csv")
write.xlsx(sctype_scores, "results/tables/sctype_scores.xlsx")
```

# plot on umap

```{r plot on umap, echo=FALSE}
bm@meta.data$sctypeclassif <- ""
for(j in unique(sctype_scores$cluster)){
  cl_type <- sctype_scores[sctype_scores$cluster==j,]
  bm@meta.data$sctypeclassif[bm@meta.data$seurat_clusters == j] <- as.character(cl_type$type[1])
}

bm %>%
    DimPlot(reduction = "umap",
            label = TRUE,
            repel = TRUE,
            group.by = 'sctypeclassif') -> umap_celltype_plot
umap_celltype_plot
# save plot to png
ggsave("results/figures/umap_celltype_plot.png", umap_celltype_plot, width = 10, height = 10)
```

# plot cell type stats
```{r plot cell type stats, echo=FALSE}
# plot cell type frequency in seurat object metadata
# by sample_id
bm %>%
  dittoBarPlot(var = "sctypeclassif", group.by = "sample") -> celltype_freq_plot
celltype_freq_plot
# save plot to png
ggsave("results/figures/celltype_freq_plot.png", celltype_freq_plot, width = 10, height = 10)

```

# group into lineages
```{r group into lineages, echo=FALSE}
# get unique cell types
bm@meta.data %>%
  dplyr::select(sctypeclassif) %>%
  unique() %>%
  as.data.frame() -> cell_types
# group into lineages
bm[["lineage"]] <- ""
# create lists
myeloid_lineage <- c("Myeloid Dendritic cells", "Neutrophils", "Classical Monocytes", "Non-classical monocytes")
lymphoid_lineage <- c("Plasma B cells", "Immature B cells", "Pro-B cells", "Pre-B cells", "Naive CD4+ T cells", "Naive CD8+ T cells", "CD8+ NKT-like cells", "Plasmacytoid Dendritic cells")
erythroid_lineage <- c("Erythroid-like and erythroid precursor cells", "Endothelial")

# Create a vector of lineage assignments for each cell based on its cell type
lineage_assignments <- ifelse(bm$sctypeclassif %in% myeloid_lineage, "Myeloid",
                              ifelse(bm$sctypeclassif %in% lymphoid_lineage, "Lymphoid",
                                     ifelse(bm$sctypeclassif %in% erythroid_lineage, "Erythroid",
                                            ifelse(bm$sctypeclassif %in% "Progenitor cells", "Progenitor cells",
                                                   "Unknown"))))
# Add the lineage metadata column to the Seurat object
bm <- AddMetaData(bm, metadata = lineage_assignments, col.name = "lineage")


# plot lineage frequency in seurat object metadata
# by sample_id
bm %>%
  dittoBarPlot(var = "lineage", group.by = "sample") -> lineage_freq_plot
lineage_freq_plot
# save plot to png
ggsave("results/figures/lineage_freq_plot.png", lineage_freq_plot, width = 10, height = 10)
```

