---
title: "Load Oetjen data"
output:
  html_notebook

---
# Load libraries

```{r}
rm(list=ls())
# suppress load messages
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(GEOquery))
```

# Download data

```{r download data}
# if folder doesnt exist, create folder
if (!dir.exists("data")) dir.create("data")
# download data
getGEOSuppFiles("GSE120221", baseDir = "data/")
```
```{r decompress tar}
# decompres tar
untar("data/GSE120221/GSE120221_RAW.tar", exdir = "data/GSE120221" )
# delete compressed file
file.remove("data/GSE120221/GSE120221_RAW.tar")
```

# Put each sample into a folder

```{r sample in folder}
data_dir <- "data/GSE120221/"
list.files(data_dir)
# obtain the sample names (GEO ID + sample name)
files <- list.files(data_dir, pattern = "mtx.gz") # unique list
# GEOID + _ + sample name
files <- sapply(strsplit(files, split='_', fixed=TRUE), function(x) (paste0(x[1], "_", strsplit(x[3], split='.mtx.gz'))))
# move every file to a folder with the sample name
for (file in files) {
  print(file)
  filename_parts <- strsplit(file, split='_', fixed=TRUE) %>% unlist() # split GEOID and sample name
  dir.create(paste0(data_dir, file)) # create a folder for the sample
  # move the files to the corresponding sample folder
  file.rename(paste0(data_dir, filename_parts[1], "_genes_", filename_parts[2], ".tsv.gz"), paste0(data_dir, file, "/features.tsv.gz")) # rename genes file to features file. This is what Seurat expects. Related to CellRanger v2 vs v3 output.
  file.rename(paste0(data_dir, filename_parts[1], "_barcodes_", filename_parts[2], ".tsv.gz"), paste0(data_dir, file, "/barcodes.tsv.gz"))
  file.rename(paste0(data_dir, filename_parts[1], "_matrix_", filename_parts[2], ".mtx.gz"), paste0(data_dir, file, "/matrix.mtx.gz"))
}
```



# Read into Seurat
```{r read into seurat}
data_dir <- "data/GSE120221/"
sample_list <- list.files(data_dir) # each folder corresponds to a sample
for (sample in sample_list) {
  print(sample)
  seurat_obj <- Read10X(data.dir = paste0(data_dir, sample))
  seurat_obj <- CreateSeuratObject(counts = seurat_obj, project = sample)
  assign(sample, seurat_obj)
}
```


# Merge samples
```{r merge samples}
# get sample names (sample_list = GEO ID + sample name)
sample_names <- sapply(strsplit(sample_list, split='_', fixed=TRUE), function(x) x[2])
# sample_list is a list of strings, to make it into a list of objects:
# sample_objects <- mget(sample_list)
# merge samples
# all_data <- merge(x = sample_objects[1], y = as.vector(sample_objects[2:length(sample_objects)]),
#                   add.cell.ids = sample_names, project = "Oetjen")
all_data <- merge(x = get(sample_list[1]), # gets the Seurat object named sample_list[1]
                  y = mget(sample_list[2:length(sample_list)]),
                  add.cell.ids = sample_names, project = "Oetjen")
all_data
```

Note, check that the number of cells (samples) in the Seurat object is correct.
In this case, it is over 90000 cells, which is correct acording to the paper.

# Save Seurat object
```{r save seurat object}
# if folder doesnt exist, create folder
if (!dir.exists("data/seurat_obj")) dir.create("data/seurat_obj")
# save object
saveRDS(all_data, file = "data/seurat_obj/Oejten_scRNAseq.rds")
```