---
title: "Progenitor Analysis"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# image size
options(jupyter.plot_mimetypes = 'image/png',
        repr.plot.width=6,
        repr.plot.height=4)
```
# Load
## load packages
```{r load packages, message=FALSE, warning=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(tidyr)
library(dittoSeq)
library(patchwork)
library(clustree)
```

## load data
```{r load data}
# load data
bm <- readRDS("data/DISCO/bmv2_fixed.rds")
```
# Subset for Progenitor cells


We can use the simplified annotation to subset for progenitor cells.
```{r subset}
# subset for CD34+ cells
bm.progenitors <- subset(bm, subset = simplified_ct == "Progenitor cells")
# take only those with sex information
bm.progenitors <- subset(bm.progenitors, subset = gender %in% c("F", "M"))
# only that can be classified under 45
bm.progenitors <- subset(bm.progenitors, subset = age_groups == "under 45")
```
# Re-process
```{r reprocess}
# prepare for integration
progenitors_list <- SplitObject(bm.progenitors, split.by = "project_id")
# find variable features
progenitors_list <- lapply(progenitors_list, function(x) {
  x <- NormalizeData(object = x, normalization.method = "LogNormalize", scale.factor = 10000)
  x <- FindVariableFeatures(object = x, selection.method = "vst", assay = "RNA")

})
# select features that are variable across all datasets
progenitors_features <- SelectIntegrationFeatures(progenitors_list)
# perform integration
bm.progenitors.anchors <- FindIntegrationAnchors(object = progenitors_list, features = progenitors_features)
bm.progenitors <- IntegrateData(anchorset = bm.progenitors.anchors, dims = 1:30)
# reprocess data
DefaultAssay(bm.progenitors) <- "integrated"
bm.progenitors <- ScaleData(object = bm.progenitors)
bm.progenitors <- RunPCA(object = bm.progenitors)
bm.progenitors <- RunUMAP(object = bm.progenitors, dims = 1:30)
bm.progenitors <- FindNeighbors(object = bm.progenitors, reduction="pca", dims = 1:30)
bm.progenitors <- FindClusters(object = bm.progenitors, resolution=0.5)
DimPlot(object = bm.progenitors, reduction = "umap", group.by = "ct", label = TRUE) -> p1
DimPlot(object = bm.progenitors, reduction = "umap", group.by = "project_id", label = TRUE) -> p2
p1 + p2
```


## save subset data
```{r save subset}
saveRDS(bm.progenitors, "data/DISCO/bmv2_fixed_progenitors.rds", compress = FALSE)
```


