---
title: "Trajectory analysis"
output:
  html_notebook:
    output_file: "Trajectory_analysis_full_DISCO.html"
---

This applies slingshot analysis to the data
Following
https://nbisweden.github.io/workshop-archive/workshop-scRNAseq/2020-01-27/labs/compiled/slingshot/slingshot.html#basic_processing_with_seurat_pipeline

# Load

load the libraries

```{r}
library(slingshot)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SingleCellExperiment)
library(scales)
library(tradeSeq)
library(RColorBrewer)

set.seed(1234)
# set color palette
pal <- c(RColorBrewer::brewer.pal(9, "Set1"), RColorBrewer::brewer.pal(8, "Set2"))
# and functions
# from https://bustools.github.io/BUS_notebooks_R/slingshot.html#introduction
#' Assign a color to each cell based on some value
#'
#' @param cell_vars Vector indicating the value of a variable associated with cells.
#' @param pal_fun Palette function that returns a vector of hex colors, whose
#' argument is the length of such a vector.
#' @param ... Extra arguments for pal_fun.
#' @return A vector of hex colors with one entry for each cell.
cell_pal <- function(cell_vars, pal_fun,...) {
  if (is.numeric(cell_vars)) {
    pal <- pal_fun(100, ...)
    return(pal[cut(cell_vars, breaks = 100)])
  } else {
    categories <- sort(unique(cell_vars))
    pal <- setNames(pal_fun(length(categories), ...), categories)
    return(pal[cell_vars])
  }
}

```

load data
```{r}
data <- readRDS("../01_Integration/immature_sex_annotated.rds")
```

```{r}
# data <- subset(data, subset = ct != "HSC" )
# # run umap
# data <- RunUMAP(data, dims = 1:20)
# data <- RunPCA(data, data)

data <-  subset(data, subset = ct %in% c("GMP", "S100A+ preNeutrophil", "Metamyelocyte/Band neutrophil",
                 "Neutrophil", "Promyelocyte", "Myelocyte"))
```
# slingshot
Convert to SCE object and import into slingshot
```{r}
Idents(data) <- data$ct
# data <- subset(data, downsample=200)
sds <- slingshot(Embeddings(data, "pca"), clusterLabels = data$ct,
                 start.clus = "GMP", stretch = 0, allow.breaks=FALSE)
# lineages <- getLineages(Embeddings(data, "umap"), clusterLabels = data$ct,
#                    start.clus="HSC")
# lineages@metadata$lineages
# curves <- getCurves(lineages, approx_points=300)

print("done")
```
Add color palettes
```{r}
cell_colors <- cell_pal(data$ct, brewer_pal("qual", "Set2"))
cell_colors_clust <- cell_pal(data$ct, hue_pal())
```
```{r}
plot1 <- DimPlot(data, group.by="ct") + NoLegend()
LabelClusters(plot1, id="ct", color=unique(ggplot_build(plot1)$data[[1]]$colour), size =5, repel=T, max.overlaps=Inf) -> plot2
plot2
curves <- slingCurves(sds, as.df = TRUE)
plot3 <- plot2 +
geom_path(data = curves %>% arrange(Order),
              aes(group = Lineage, x=UMAP_1, y=UMAP_2))
plot3
# ggsave("full.png", plot2, dpi=600, width = 16, height = 9 )

plot1 <- DimPlot(data, group.by="ct", reduction = "pca") + NoLegend()
LabelClusters(plot1, id="ct", color=unique(ggplot_build(plot1)$data[[1]]$colour), size =5, repel=T, max.overlaps=Inf) -> plot2
plot2
curves <- slingCurves(sds, as.df = TRUE)
plot3 <- plot2 +
geom_path(data = curves %>% arrange(Order),
              aes(group = Lineage, x=PC_1, y=PC_2))
plot3


```

```{r}
plot(Embeddings(data, "umap"), asp=1, pch=16, col=brewer.pal(3, "Set1")[factor(data$gender)], las=1)
lines(SlingshotDataSet(sds), lwd=3)
legend(-15, 12, legend = c("F", "M"), title = "Sex", pch=16, col = brewer.pal(3,'Set1')[1:2])

plot(Embeddings(data, "umap"), asp=1, pch=16, col= cell_colors_clust, las=1)
lines(SlingshotDataSet(sds), lwd=3)
legend(-15, 12, legend = c("F", "M"), title = "cell type", pch=16, col = brewer.pal(3,'Set1')[1:2])
# for pca
plot(Embeddings(data, "pca"), asp=1, pch=16, col= brewer.pal(3, "Set1")[factor(data$gender)], las=1)
lines(SlingshotDataSet(sds), lwd=3)
legend(-15, 12, legend = c("F", "M"), title = "Sex", pch=16, col = brewer.pal(3,'Set1')[1:2])

```

```{r}
n <- nrow(Embeddings(data, "umap"))
L <- ncol(slingPseudotime(sds))
noise <- runif(n, -0.1, 0.1)
plot(as.numeric(slingPseudotime(sds)), rep(1:L, each=n) + noise, pch=16, col=brewer.pal(9, "Set1")[factor(data$gender)], las=1, xlab="Pseudotime", ylab="Lineage")
axis(1);axis(2, at=1:L, las=1)
plot(as.numeric(slingPseudotime(sds)), rep(1:L, each=n) + noise, pch=16,
     col=colorRampPalette(brewer.pal(9, "Set1"))(60)[factor(data$ct)], las=1,
     xlab="Pseudotime", ylab="Lineage")
axis(1);axis(2, at=1:L, las=1)
plot(as.numeric(slingPseudotime(sds)), rep(1:L, each=n) + noise, pch=16, col= cell_colors_clust, las=1, xlab="Pseudotime", ylab="Lineage")
axis(1);axis(2, at=1:L, las=1)
```

```{r}
layout(matrix(1:2, nrow=1))
boxplot(slingPseudotime(sds)[,1] ~factor(data$gender),
        col=brewer.pal(3, "Set1")[1:2], main="Lineage 1",
xlab='Sex', ylab='Pseudotime')
# boxplot(slingPseudotime(sds)[,2] ~factor(data$gender),
#         col=brewer.pal(3, "Set1")[1:2], main="Lineage 2",
# xlab='Sex', ylab='Pseudotime')
```

tradeSeq
```{r}
# BiocParallel::register(BiocParallel::SerialParam())
BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 10

genes_sel <- read.csv("../VR/2023_06_14_14_17_13/tables/Time.group.5.Linear.csv")
top_100 <- genes_sel %>% slice_max(-cor, n=100) %>% pull(Gene.Name)
counts <- as.matrix(data@assays$raw@counts)
filt_counts <- counts[rowSums(counts > 5) > ncol(counts)/100, ] # at least 5 counts, in at least 1% of cells
dim(filt_counts)
sce <- fitGAM(counts=filt_counts, sds = as.SlingshotDataSet(sds), parallel = TRUE, BPPARAM = BPPARAM)
```

## genes that change with pseudotime
```{r}
# Define function to plot
clustering <- "ct"
plot_differential_expression <- function(feature_id) {
    feature_id <- pseudotime_association %>% filter(pvalue < 0.05) %>% top_n(1, -waldStat) %>% pull(feature_id)
    cowplot::plot_grid(plotGeneCount(sds, filt_counts, gene = "S100A9", clusters = clustering, models = sce) + ggplot2::theme(legend.position = "none"),

                       plotSmoothers(sce, as.matrix(counts), gene = feature_id[1]))
}
```


```{r}
pseudotime_association <- associationTest(sce)
pseudotime_association$fdr <- p.adjust(pseudotime_association$pvalue, method = "fdr")
pseudotime_association <- pseudotime_association[order(pseudotime_association$pvalue), ]
pseudotime_association$feature_id <- rownames(pseudotime_association)
```

```{r}
feature_id <- pseudotime_association %>% filter(pvalue < 0.05) %>% top_n(1, -waldStat) %>% pull(feature_id)
plot_differential_expression(feature_id)
```


pattern test for differences between lineages
```{r}
pattern_association <- patternTest(sce)
oPat <- order(pattern_association$waldStat, decreasing = TRUE)
head(rownames(pattern_association)[oPat])
```
```{r}
plotSmoothers(sce, as.matrix(counts), gene=rownames(pattern_association)[oPat[1]], pointCol = "Predicted_sex")
plotSmoothers(sce, as.matrix(counts), gene=rownames(pattern_association)[oPat[2]], pointCol = "Predicted_sex")
plotSmoothers(sce, as.matrix(counts), gene=rownames(pattern_association)[oPat[3]], pointCol = "Predicted_sex")
plotSmoothers(sce, as.matrix(counts), gene=rownames(pattern_association)[oPat[4]], pointCol = "Predicted_sex")

```
```{r}
#condition
sce_c <- fitGAM(counts=filt_counts, sds = as.SlingshotDataSet(sds), parallel = TRUE, BPPARAM = BPPARAM, conditions = factor(data$gender))
data_sce <- as.SingleCellExperiment(data)
coldata <- cbind(colData(sce_c), colData(data_sce))
colData(sce_c) <- DataFrame(coldata)
condition_association <- conditionTest(sce_c )
oCond <- order(condition_association$waldStat, decreasing = TRUE)
head(rownames(condition_association)[oCond])
```
```{r}
gene_to_plot <- rownames(condition_association)[oCond[1]]
metadata_colour <- "ct"
plotSmoothers(sce_c, as.matrix(counts), gene=gene_to_plot, pointCol = metadata_colour) +
labs(title = gene_to_plot)
gene_to_plot <- rownames(condition_association)[oCond[2]]
plotSmoothers(sce_c, as.matrix(counts), gene=gene_to_plot, pointCol = metadata_colour) +
labs(title = gene_to_plot)
gene_to_plot <- rownames(condition_association)[oCond[length(oCond)]]
plotSmoothers(sce_c, as.matrix(counts), gene=gene_to_plot, pointCol = metadata_colour) +
labs(title = gene_to_plot)
```





plot the trajectory and the principal curves (smoothed trajectories)
```{r}

plot(SlingshotDataSet(sds), col = cell_colors, pch = 16, cex = 0.5, type = "b")
# lines(sds, lwd = 2, type = 'lineages', col = 'black')
DimPlot(data, reduction = "umap", group.by = "ct", label = TRUE, pt.size = 0.5) +
NoLegend() -> p
curves <- slingCurves(sds, as.df = TRUE)
curves <- curves %>%
        filter(Lineage == 7)
p + geom_path(data = curves %>% arrange(Order),
              aes(group = Lineage, x=UMAP_1, y=UMAP_2))-> p
p
ggsave("a.png", p)
```





