---
title: "Post cellexalvr"
output: html_notebook
---

# load

libraries
```{r}
library(tidyverse)
library(ggplot2)
library(Seurat)
library(patchwork)
library(dittoSeq)
library(plotly)
```

data
```{r}
# set working directory
setwd("/home/inf-38-2022/MScProject/")
data <- readRDS("01_Integration/immature_sex_annotated.rds")
```

# Add clustering selection information
```{r}
# read file
genes_sel <- read_csv("VR/2023_06_14_14_17_13/tables/Time.group.5.Linear.csv")
colnames(genes_sel) <- c("Gene_name", colnames(genes_sel)[2:ncol(genes_sel)])
cell_sel <- read_tsv("VR/2023_06_14_14_17_13/TimeSelection.Time.group.5.txt", col_names  = FALSE)
colnames(cell_sel) <- c("cell", "color", "reduction", "cluster")
rownames(cell_sel) <- cell_sel$cell
# expand cluster names to match seurat
all_cell_sel <- colnames(data) %>%
  as.data.frame() %>%
  left_join(cell_sel, by = c("." = "cell"))
```


```{r}
# add metadata to seurat
data <- AddMetaData(data, metadata = all_cell_sel$cluster, col.name = "cellexalvr_cluster_5")
data <- AddMetaData(data, metadata = all_cell_sel$color, col.name = "cellexalvr_color_5")
subset_data <- subset(data, subset = cellexalvr_cluster_5 != "NA")
```


# plot

## plot gene expression per cluster
```{r}
# genes to show from gene_sel
genes_to_show <- c(head(genes_sel, 2)$Gene_name, tail(genes_sel, 2)$Gene_name)
# plot gene expression per cluster
p1 <- VlnPlot(data, features = genes_to_show, pt.size = 0, group.by = "cellexalvr_cluster_5")
p1
Idents(subset_data) <- subset_data$cellexalvr_cluster_5
avg_expr <- AverageExpression(subset_data, features = genes_to_show, assays = "RNA" , return.seurat = TRUE, add.ident = "cellexalvr_cluster_5", )
levels(avg_expr) <- c(1,2,3,4,5,6,7,8,9,10)
p2 <- DoHeatmap(avg_expr, features = genes_to_show, group.by = "ident")
p2
avg_expr_data <- avg_expr[["RNA"]]@scale.data %>%
  t() %>%
  as.data.frame()
rownames(avg_expr_data) <-  rownames(avg_expr_data) %>%
  str_remove_all(regex("_[:digit:]*")) %>%
  as.numeric()
avg_expr_data %>%
  mutate(ident = rownames(avg_expr_data) %>% as.numeric()) %>%
  arrange(ident) %>%
  pivot_longer(-ident, names_to = "gene", values_to = "scaled_expr") %>%
ggplot(aes(x = ident, y = scaled_expr)) +
  geom_line(aes(color = gene)) +
  theme_bw()

```

## plot cell type
```{r}
dittoBarPlot(data, var= "ct", group.by = "cellexalvr_cluster_5",
             x.reorder = c(1,3,4,5,6,7,8,9,10,2))
dittoBarPlot(data, var= "ct", group.by = "cellexalvr_cluster_5",
             x.reorder = c(1,3,4,5,6,7,8,9,10,2), do.hover = TRUE)
```

# 3d umap
```{r}
data <- RunUMAP(data, reduction.name = "3d", dims = 1:30, n.components = 3)
```

```{r}

plot_data %>%
  distinct(cellexalvr_color_5, cellexalvr_cluster_5) %>%
  arrange(cellexalvr_cluster_5) %>%
  select(cellexalvr_color_5) %>%
  as.vector() %>%
  unlist()-> colors
plot_data <- FetchData(data, vars = c("x3d_1", "x3d_2", "x3d_3", "ct", "cellexalvr_cluster_5", "cellexalvr_color_5"))
plot_data %>%
        plot_ly(x=~x3d_1, y=~x3d_2, z=~x3d_3,
    color = ~cellexalvr_cluster_5,
  colors = colors
        ) -> p3d_clusters
plot_data %>%
        plot_ly(x=~x3d_1, y=~x3d_2, z=~x3d_3,
    color = ~ct
        ) -> p3d_ct
p3d_clusters
p3d_ct
htmlwidgets::saveWidget(p3d_clusters, "VR/2023_06_14_14_17_13/3d_clusters.html", selfcontained = TRUE)
htmlwidgets::saveWidget(p3d_ct, "VR/2023_06_14_14_17_13/3d_ct.html", selfcontained = TRUE)
```

# for spring

load data
```{r}
read.csv("SPRING/coordinates_subset_bm.txt") -> coordinates_spring
colnames(coordinates_spring) <- c("x", "y", "z")
```
```{r}

# plot_data %>%
#   distinct(cellexalvr_color_5, cellexalvr_cluster_5) %>%
#   arrange(cellexalvr_cluster_5) %>%
#   select(cellexalvr_color_5) %>%
#   as.vector() %>%
#   unlist()-> colors
coordinates_spring %>%
        plot_ly(x=~x, y=~y, z=~z) -> plot

plot
# htmlwidgets::saveWidget(p3d_clusters, "VR/2023_06_14_14_17_13/3d_clusters.html", selfcontained = TRUE)
# htmlwidgets::saveWidget(p3d_ct, "VR/2023_06_14_14_17_13/3d_ct.html", selfcontained = TRUE)
```

