---
title: "Sex assignment with cellXY"
output: html_notebook
---


```{r}
library(cellXY)
library(SingleCellExperiment)
library(org.Hs.eg.db)
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyr)
library(dittoSeq)
# library(lim4)
seurat_obj <- readRDS("data/seurat_obj/Oejten_scRNAseq.rds")
sc_data <- as.SingleCellExperiment(seurat_obj)
counts <- counts(sc_data)
```

Find doublets
```{r}
db_pred <- findMfDoublet(x = counts, genome = "Hs")
db_pred$sex <- sc_data$sex
print(table(db_pred$prediction, db_pred$sex))
```


Assign sex

```{r}
# this is useful if they come in a different format
# ann <- select(org.Hs.eg.db, keys=rownames(sc_data),
#               columns=c("GENENAME", "SYMBOL"), keytype="SYMBOL")
# m <- match(rownames(counts), ann$GENENAME)
# rownames(counts) <- ann$SYMBOL[m]
sex <- classifySex(counts, genome="Hs")
table(sex$prediction)
boxplot(counts["XIST",]~sex$prediction, ylim=c(0, 5))
```



# add metadata
```{r}
seurat_obj <- AddMetaData(seurat_obj, metadata = sex, col.name = "cell_sex_predicted")
```
## plot sex freq
```{r}
seurat_obj %>% dittoBarPlot(var = "cell_sex_predicted", group.by = "sample")
```

```{r}
library(ggplot2)
bar_data <- as.data.frame(table(seurat_obj@meta.data$cell_sex_predicted, seurat_obj@meta.data$sample))
colnames(bar_data) <- c("Sex", "Sample", "Count")
ggplot(bar_data, aes(x = Sample, y = Count, fill = Sex)) +
  geom_col(position = "fill") +
  labs(x = "Sample", y = "Count", fill = "Sex") +
  theme_bw()
```


# DISCO bm v2
```{r}
disco_bm_v2 <- readRDS("data/DISCO/bmv2_fixed.rds")
sc_data <- as.SingleCellExperiment(disco_bm_v2)

counts <- counts(sc_data)

sexbm <- classifySex(counts, genome="Hs")

table(sexbm$prediction)
boxplot(counts["XIST",]~sexbm$prediction)
```

# add metadata
```{r}
disco_bm_v2 <- AddMetaData(disco_bm_v2, metadata = sexbm, col.name = "cell_sex_predicted")
```
## plot sex freq
```{r}
disco_bm_v2@meta.data %>%
  distinct(sample_id, gender, subject_id, project_id, platform, age, age_group, cell_sorting, fetal_age_week) -> gender_indiv
gender_indiv

disco_bm_v2 %>%
  dittoBarPlot(var = "sex_predicted", group.by = "sample_id", split.by = "project_id", split.adjust = list(scales = "free")) -> sex_prediction_disco_bm_v2
# same but with base ggplot


sex_prediction_disco_bm_v2
```

# assign sex to individuals
```{r}
# data <- disco_bm_v2
# data <- AddMetaData(data, metadata = data@meta.data$gender, col.name = "sex" )
data@meta.data %>%
group_by (sample, cell_sex_predicted, sex, project_id) %>%
count() %>%
  group_by(sample) %>%
mutate(freq = n/sum(n)) %>%
  pivot_wider(names_from=cell_sex_predicted, values_from=c(n,freq))%>%
  # if Female > 80%, female
mutate(sample_sex = ifelse(freq_Female >= 0.70 | freq_Female/freq_Male >= 2, "F",
                           ifelse(freq_Male >= 0.70 | freq_Male/freq_Female >= 2, "M",
                                  "incluncusive"))) -> sex_assi
sex_assi
```

Check results
```{r}
sex_assi %>%
mutate(match = ifelse(sex == sample_sex, "match", "no_match")) -> sex_assi
sex_assi
```

# add metadata
```{r}
# add metadata to the seurat object
data[["sample"]] %>%
left_join(sex_assi, by = c("sample" = "sample")) -> sex_assi_metadata
sex_assi_metadata
data <- AddMetaData(data, metadata = sex_assi_metadata$sample_sex, col.name = "pred_sex")
```

# save seurat obj
```{r, eval = FALSE}
saveRDS(disco_bm_v2, "data/DISCO/bmv2_fixed.rds", compress = FALSE)
```